import { useEffect, useState } from "react";
import { listDatasets, uploadDataset } from "../services/api";

export default function SatellitePage() {
  const [datasets, setDatasets] = useState([]); const [file, setFile] = useState(null); const [message, setMessage] = useState("");
  const load = async () => { try { setDatasets((await listDatasets()).filter((item) => item.kind === "satellite")); } catch (error) { setMessage(error.message); } };
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); if (!file) return; try { const item = await uploadDataset("satellite", file); setDatasets((current) => [item, ...current]); setFile(null); event.target.reset(); setMessage("Satellite scene validated and stored."); } catch (error) { setMessage(error.message); } };
  return <div className="page-stack"><section className="page-heading"><div><p className="eyebrow">Phase 8 · observation data</p><h2>Satellite monitoring</h2><p>Upload GeoTIFF or GeoJSON flood extents from Sentinel or Google Earth Engine workflows.</p></div></section>{message && <div className="notice">{message}<button onClick={() => setMessage("")}>×</button></div>}<section className="content-grid"><form className="panel mini-form" onSubmit={submit}><div className="panel-title"><div><span className="eyebrow">Scene ingestion</span><h2>Add satellite scene</h2></div></div><label>Scene file<input required type="file" accept=".tif,.tiff,.geojson,.json" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label><small className="form-help">Accepted: .tif, .tiff, .geojson, .json</small><button className="primary-button" type="submit">Validate scene</button></form><article className="panel dataset-info"><span className="info-icon">◌</span><h2>Change detection ready</h2><p>Validated scenes are kept outside the database with API metadata for later date and extent comparisons.</p></article></section><section className="panel table-panel"><div className="panel-title"><div><span className="eyebrow">Stored observations</span><h2>Satellite scenes</h2></div><button className="text-button" onClick={load}>Refresh</button></div>{datasets.length === 0 ? <p className="empty-state">No satellite scenes uploaded yet.</p> : <div className="table-wrap"><table><thead><tr><th>File</th><th>Format</th><th>Size</th><th>Metadata</th></tr></thead><tbody>{datasets.map((item) => <tr key={item.id}><td>{item.filename}</td><td>{item.filename.split(".").pop().toUpperCase()}</td><td>{(item.size_bytes / 1024).toFixed(1)} KB</td><td>{item.metadata_json || "Stored"}</td></tr>)}</tbody></table></div>}</section></div>;
}
