import { useEffect, useState } from "react";
import { getSimulationResult, listProjects, listSimulations, runScenarios } from "../services/api";

const defaults = { project_id: "", dam: "Rishi Ganga", water_level: 1850, reservoir_volume: 5.7, breach_width: 100, breach_time: 30, duration_hours: 24 };

export default function ScenariosPage() {
  const [projects, setProjects] = useState([]);
  const [runs, setRuns] = useState([]);
  const [form, setForm] = useState(defaults);
  const [message, setMessage] = useState("");
  const load = async () => { try { const [projectData, simulationData] = await Promise.all([listProjects(), listSimulations()]); const scenarioRuns = await Promise.all(simulationData.filter((item) => item.dam.includes(" - ")).map(async (item) => ({ ...item, result: item.status === "completed" ? await getSimulationResult(item.id).catch(() => null) : null }))); setProjects(projectData); setRuns(scenarioRuns); if (!form.project_id && projectData[0]) setForm((current) => ({ ...current, project_id: projectData[0].id })); } catch (error) { setMessage(error.message); } };
  useEffect(() => { load(); const timer = window.setInterval(load, 3000); return () => window.clearInterval(timer); }, []);
  const update = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); try { await runScenarios({ ...form, project_id: Number(form.project_id), water_level: Number(form.water_level), reservoir_volume: Number(form.reservoir_volume), breach_width: Number(form.breach_width), breach_time: Number(form.breach_time), duration_hours: Number(form.duration_hours) }); setMessage("Normal, moderate, and extreme scenarios queued."); load(); } catch (error) { setMessage(error.message); } };
  return <div className="page-stack"><section className="page-heading"><div><p className="eyebrow">Phase 7 · scenario analysis</p><h2>Scenario comparison</h2><p>Run three consistent dam-break assumptions and compare their completed flood metrics.</p></div></section>
    {message && <div className="notice">{message}<button onClick={() => setMessage("")}>×</button></div>}
    <form className="panel mini-form scenario-form" onSubmit={submit}><div className="panel-title"><div><span className="eyebrow">Batch simulation</span><h2>Run three scenarios</h2></div></div><label>Project<select required name="project_id" value={form.project_id} onChange={update}><option value="">Choose a project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><div className="form-grid"><label>Dam<input name="dam" value={form.dam} onChange={update} /></label><label>Water level (m)<input name="water_level" type="number" value={form.water_level} onChange={update} /></label><label>Reservoir volume (MCM)<input name="reservoir_volume" type="number" step="0.1" value={form.reservoir_volume} onChange={update} /></label><label>Breach width (m)<input name="breach_width" type="number" value={form.breach_width} onChange={update} /></label><label>Formation time (min)<input name="breach_time" type="number" value={form.breach_time} onChange={update} /></label><label>Duration (hours)<input name="duration_hours" type="number" value={form.duration_hours} onChange={update} /></label></div><button className="primary-button" type="submit">Run scenario set <span>→</span></button></form>
    <section className="panel table-panel"><div className="panel-title"><div><span className="eyebrow">Live comparison</span><h2>Scenario runs</h2></div><button className="text-button" onClick={load}>Refresh</button></div>{runs.length === 0 ? <p className="empty-state">Run a scenario set to populate this comparison.</p> : <div className="table-wrap"><table><thead><tr><th>Scenario</th><th>Status</th><th>Max depth</th><th>Velocity</th><th>Area</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id}><td>{run.dam.split(" · ").pop()}</td><td><span className="badge queued-badge">{run.status}</span></td><td>{run.result ? `${run.result.max_depth} m` : "Processing"}</td><td>{run.result ? `${run.result.max_velocity} m/s` : "-"}</td><td>{run.result ? `${run.result.inundated_area_km2} km²` : "-"}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}
